// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3O-MOqpxDrlOixukzNwm6qISutuhSvgQ',
    appId: '1:449527671032:web:37ece8ba459f7a2b8ab30d',
    messagingSenderId: '449527671032',
    projectId: 'maid-in-kenya-app',
    authDomain: 'maid-in-kenya-app.firebaseapp.com',
    storageBucket: 'maid-in-kenya-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBYwJwdv86_bzBYYJ0xAKEsW1h_KEVhxw',
    appId: '1:449527671032:android:1a9ba0839578c1ba8ab30d',
    messagingSenderId: '449527671032',
    projectId: 'maid-in-kenya-app',
    storageBucket: 'maid-in-kenya-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7FaRlzs9kCp4LL7Wc7yfARgiwV1r_HXo',
    appId: '1:449527671032:ios:4787d6db3fc3fdd48ab30d',
    messagingSenderId: '449527671032',
    projectId: 'maid-in-kenya-app',
    storageBucket: 'maid-in-kenya-app.appspot.com',
    iosClientId: '449527671032-vpfidhih02vi508tjoppah3okgq6lhs5.apps.googleusercontent.com',
    iosBundleId: 'hillary.co.ke.maidinkenya',
  );
}
